/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FHEVMTestSuite5Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "add_euint16_uint16"
      | "add_euint8_uint8"
      | "add_uint16_euint16"
      | "add_uint8_euint8"
      | "and_euint128_euint256"
      | "and_euint16_uint16"
      | "and_euint256_euint128"
      | "and_euint256_euint16"
      | "and_euint256_euint256"
      | "and_euint256_euint32"
      | "and_euint256_euint64"
      | "and_euint256_euint8"
      | "and_euint8_uint8"
      | "and_uint16_euint16"
      | "and_uint8_euint8"
      | "div_euint16_uint16"
      | "div_euint8_uint8"
      | "eq_euint128_euint128"
      | "eq_euint128_euint256"
      | "eq_euint16_uint16"
      | "eq_euint256_euint128"
      | "eq_euint256_euint16"
      | "eq_euint256_euint256"
      | "eq_euint256_euint32"
      | "eq_euint256_euint64"
      | "eq_euint256_euint8"
      | "eq_euint8_uint8"
      | "eq_uint8_euint8"
      | "ge_euint128_euint128"
      | "ge_euint8_uint8"
      | "ge_uint8_euint8"
      | "gt_euint128_euint128"
      | "gt_euint8_uint8"
      | "gt_uint8_euint8"
      | "le_euint128_euint128"
      | "le_euint8_uint8"
      | "le_uint8_euint8"
      | "lt_euint128_euint128"
      | "lt_euint8_uint8"
      | "lt_uint8_euint8"
      | "max_euint128_euint128"
      | "max_euint8_uint8"
      | "max_uint8_euint8"
      | "min_euint128_euint128"
      | "min_euint8_uint8"
      | "min_uint8_euint8"
      | "mul_euint16_uint16"
      | "mul_euint8_uint8"
      | "mul_uint16_euint16"
      | "mul_uint8_euint8"
      | "ne_euint128_euint128"
      | "ne_euint128_euint256"
      | "ne_euint256_euint128"
      | "ne_euint256_euint16"
      | "ne_euint256_euint256"
      | "ne_euint256_euint32"
      | "ne_euint256_euint64"
      | "ne_euint256_euint8"
      | "ne_euint8_uint8"
      | "ne_uint8_euint8"
      | "or_euint128_euint128"
      | "or_euint128_euint256"
      | "or_euint16_uint16"
      | "or_euint256_euint128"
      | "or_euint256_euint16"
      | "or_euint256_euint256"
      | "or_euint256_euint32"
      | "or_euint256_euint64"
      | "or_euint256_euint8"
      | "or_euint8_uint8"
      | "or_uint16_euint16"
      | "or_uint8_euint8"
      | "rem_euint16_uint16"
      | "rem_euint8_uint8"
      | "resEbool"
      | "resEuint128"
      | "resEuint16"
      | "resEuint256"
      | "resEuint32"
      | "resEuint64"
      | "resEuint8"
      | "sub_euint16_uint16"
      | "sub_euint8_uint8"
      | "sub_uint16_euint16"
      | "sub_uint8_euint8"
      | "xor_euint128_euint128"
      | "xor_euint128_euint256"
      | "xor_euint16_uint16"
      | "xor_euint256_euint128"
      | "xor_euint256_euint16"
      | "xor_euint256_euint256"
      | "xor_euint256_euint32"
      | "xor_euint256_euint64"
      | "xor_euint256_euint8"
      | "xor_euint8_uint8"
      | "xor_uint16_euint16"
      | "xor_uint8_euint8"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DebugVerify"): EventFragment;

  encodeFunctionData(
    functionFragment: "add_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "add_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "add_uint16_euint16",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "add_uint8_euint8",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint128_euint256",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint256_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint256_euint16",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint256_euint256",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint256_euint32",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint256_euint64",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint256_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_uint16_euint16",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_uint8_euint8",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "div_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "div_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint128_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint128_euint256",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint256_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint256_euint16",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint256_euint256",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint256_euint32",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint256_euint64",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint256_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_uint8_euint8",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ge_euint128_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ge_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ge_uint8_euint8",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt_euint128_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt_uint8_euint8",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le_euint128_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le_uint8_euint8",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt_euint128_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt_uint8_euint8",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max_euint128_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max_uint8_euint8",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "min_euint128_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "min_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "min_uint8_euint8",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul_uint16_euint16",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul_uint8_euint8",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint128_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint128_euint256",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint256_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint256_euint16",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint256_euint256",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint256_euint32",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint256_euint64",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint256_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_uint8_euint8",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint128_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint128_euint256",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint256_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint256_euint16",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint256_euint256",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint256_euint32",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint256_euint64",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint256_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_uint16_euint16",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_uint8_euint8",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rem_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rem_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "resEbool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resEuint128",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resEuint16",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resEuint256",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resEuint32",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resEuint64",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "resEuint8", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sub_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub_uint16_euint16",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub_uint8_euint8",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint128_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint128_euint256",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint256_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint256_euint16",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint256_euint256",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint256_euint32",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint256_euint64",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint256_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_uint16_euint16",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_uint8_euint8",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "add_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_uint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_uint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint128_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint256_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint256_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint256_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint256_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint256_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint256_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_uint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_uint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "div_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "div_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint128_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint256_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint256_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint256_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint256_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint256_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint256_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_uint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ge_euint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ge_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ge_uint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gt_euint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gt_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gt_uint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "le_euint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "le_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "le_uint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lt_euint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lt_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lt_uint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "max_euint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "max_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "max_uint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "min_euint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "min_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "min_uint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mul_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mul_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mul_uint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mul_uint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint128_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint256_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint256_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint256_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint256_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint256_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint256_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_uint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint128_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint256_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint256_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint256_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint256_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint256_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint256_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_uint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_uint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rem_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rem_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resEbool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resEuint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resEuint16", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resEuint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resEuint32", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resEuint64", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resEuint8", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sub_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sub_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sub_uint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sub_uint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint128_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint256_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint256_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint256_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint256_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint256_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint256_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_uint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_uint8_euint8",
    data: BytesLike
  ): Result;
}

export namespace DebugVerifyEvent {
  export type InputTuple = [
    inputHandle: BytesLike,
    inputProof: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    inputHandle: string,
    inputProof: string,
    result: string
  ];
  export interface OutputObject {
    inputHandle: string;
    inputProof: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHEVMTestSuite5 extends BaseContract {
  connect(runner?: ContractRunner | null): FHEVMTestSuite5;
  waitForDeployment(): Promise<this>;

  interface: FHEVMTestSuite5Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  add_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  add_uint16_euint16: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  add_uint8_euint8: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint128_euint256: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint256_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint256_euint16: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint256_euint256: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint256_euint32: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint256_euint64: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint256_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_uint16_euint16: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_uint8_euint8: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  div_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  div_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint128_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint128_euint256: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint256_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint256_euint16: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint256_euint256: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint256_euint32: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint256_euint64: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint256_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_uint8_euint8: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ge_euint128_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ge_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ge_uint8_euint8: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  gt_euint128_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  gt_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  gt_uint8_euint8: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  le_euint128_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  le_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  le_uint8_euint8: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  lt_euint128_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  lt_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  lt_uint8_euint8: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  max_euint128_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  max_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  max_uint8_euint8: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  min_euint128_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  min_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  min_uint8_euint8: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  mul_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  mul_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  mul_uint16_euint16: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  mul_uint8_euint8: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint128_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint128_euint256: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint256_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint256_euint16: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint256_euint256: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint256_euint32: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint256_euint64: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint256_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_uint8_euint8: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint128_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint128_euint256: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint256_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint256_euint16: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint256_euint256: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint256_euint32: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint256_euint64: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint256_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_uint16_euint16: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_uint8_euint8: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rem_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rem_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  resEbool: TypedContractMethod<[], [string], "view">;

  resEuint128: TypedContractMethod<[], [string], "view">;

  resEuint16: TypedContractMethod<[], [string], "view">;

  resEuint256: TypedContractMethod<[], [string], "view">;

  resEuint32: TypedContractMethod<[], [string], "view">;

  resEuint64: TypedContractMethod<[], [string], "view">;

  resEuint8: TypedContractMethod<[], [string], "view">;

  sub_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  sub_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  sub_uint16_euint16: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  sub_uint8_euint8: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint128_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint128_euint256: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint256_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint256_euint16: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint256_euint256: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint256_euint32: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint256_euint64: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint256_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_uint16_euint16: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_uint8_euint8: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "add_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "add_uint16_euint16"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "add_uint8_euint8"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint128_euint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint256_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint256_euint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint256_euint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint256_euint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint256_euint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint256_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_uint16_euint16"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_uint8_euint8"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "div_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "div_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint128_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint128_euint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint256_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint256_euint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint256_euint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint256_euint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint256_euint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint256_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_uint8_euint8"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ge_euint128_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ge_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ge_uint8_euint8"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt_euint128_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt_uint8_euint8"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "le_euint128_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "le_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "le_uint8_euint8"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt_euint128_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt_uint8_euint8"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max_euint128_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max_uint8_euint8"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "min_euint128_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "min_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "min_uint8_euint8"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mul_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mul_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mul_uint16_euint16"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mul_uint8_euint8"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint128_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint128_euint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint256_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint256_euint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint256_euint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint256_euint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint256_euint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint256_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_uint8_euint8"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint128_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint128_euint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint256_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint256_euint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint256_euint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint256_euint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint256_euint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint256_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_uint16_euint16"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_uint8_euint8"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rem_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rem_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resEbool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint128"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint16"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint256"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint32"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint64"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint8"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sub_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub_uint16_euint16"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub_uint8_euint8"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint128_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint128_euint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint256_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint256_euint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint256_euint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint256_euint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint256_euint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint256_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_uint16_euint16"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_uint8_euint8"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DebugVerify"
  ): TypedContractEvent<
    DebugVerifyEvent.InputTuple,
    DebugVerifyEvent.OutputTuple,
    DebugVerifyEvent.OutputObject
  >;

  filters: {
    "DebugVerify(bytes32,bytes,bytes32)": TypedContractEvent<
      DebugVerifyEvent.InputTuple,
      DebugVerifyEvent.OutputTuple,
      DebugVerifyEvent.OutputObject
    >;
    DebugVerify: TypedContractEvent<
      DebugVerifyEvent.InputTuple,
      DebugVerifyEvent.OutputTuple,
      DebugVerifyEvent.OutputObject
    >;
  };
}
