/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FHEVMTestSuite6Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "add_euint128_uint128"
      | "add_euint32_uint32"
      | "add_euint64_uint64"
      | "add_uint128_euint128"
      | "add_uint32_euint32"
      | "add_uint64_euint64"
      | "and_euint128_uint128"
      | "and_euint32_uint32"
      | "and_euint64_uint64"
      | "and_uint128_euint128"
      | "and_uint32_euint32"
      | "and_uint64_euint64"
      | "div_euint128_uint128"
      | "div_euint32_uint32"
      | "div_euint64_uint64"
      | "eq_euint128_uint128"
      | "eq_euint32_uint32"
      | "eq_euint64_uint64"
      | "eq_uint16_euint16"
      | "eq_uint32_euint32"
      | "eq_uint64_euint64"
      | "ge_euint16_uint16"
      | "ge_euint32_uint32"
      | "ge_euint64_uint64"
      | "ge_uint16_euint16"
      | "ge_uint32_euint32"
      | "ge_uint64_euint64"
      | "gt_euint16_uint16"
      | "gt_euint32_uint32"
      | "gt_euint64_uint64"
      | "gt_uint16_euint16"
      | "gt_uint32_euint32"
      | "gt_uint64_euint64"
      | "le_euint16_uint16"
      | "le_euint32_uint32"
      | "le_euint64_uint64"
      | "le_uint16_euint16"
      | "le_uint32_euint32"
      | "le_uint64_euint64"
      | "lt_euint16_uint16"
      | "lt_euint32_uint32"
      | "lt_euint64_uint64"
      | "lt_uint16_euint16"
      | "lt_uint32_euint32"
      | "lt_uint64_euint64"
      | "max_euint16_uint16"
      | "max_euint32_uint32"
      | "max_euint64_uint64"
      | "max_uint16_euint16"
      | "max_uint32_euint32"
      | "max_uint64_euint64"
      | "min_euint16_uint16"
      | "min_euint32_uint32"
      | "min_euint64_uint64"
      | "min_uint16_euint16"
      | "min_uint32_euint32"
      | "min_uint64_euint64"
      | "mul_euint128_uint128"
      | "mul_euint32_uint32"
      | "mul_euint64_uint64"
      | "mul_uint128_euint128"
      | "mul_uint32_euint32"
      | "mul_uint64_euint64"
      | "ne_euint16_uint16"
      | "ne_euint32_uint32"
      | "ne_euint64_uint64"
      | "ne_uint16_euint16"
      | "ne_uint32_euint32"
      | "ne_uint64_euint64"
      | "or_euint128_uint128"
      | "or_euint32_uint32"
      | "or_euint64_uint64"
      | "or_uint128_euint128"
      | "or_uint32_euint32"
      | "or_uint64_euint64"
      | "rem_euint128_uint128"
      | "rem_euint32_uint32"
      | "rem_euint64_uint64"
      | "resEbool"
      | "resEuint128"
      | "resEuint16"
      | "resEuint256"
      | "resEuint32"
      | "resEuint64"
      | "resEuint8"
      | "sub_euint128_uint128"
      | "sub_euint32_uint32"
      | "sub_euint64_uint64"
      | "sub_uint128_euint128"
      | "sub_uint32_euint32"
      | "sub_uint64_euint64"
      | "xor_euint128_uint128"
      | "xor_euint32_uint32"
      | "xor_euint64_uint64"
      | "xor_uint128_euint128"
      | "xor_uint32_euint32"
      | "xor_uint64_euint64"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DebugVerify"): EventFragment;

  encodeFunctionData(
    functionFragment: "add_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "add_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "add_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "add_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "add_uint32_euint32",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "add_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_uint32_euint32",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "div_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "div_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "div_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_uint16_euint16",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_uint32_euint32",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ge_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ge_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ge_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ge_uint16_euint16",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ge_uint32_euint32",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ge_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt_uint16_euint16",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt_uint32_euint32",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le_uint16_euint16",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le_uint32_euint32",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt_uint16_euint16",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt_uint32_euint32",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max_uint16_euint16",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max_uint32_euint32",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "min_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "min_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "min_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "min_uint16_euint16",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "min_uint32_euint32",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "min_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul_uint32_euint32",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_uint16_euint16",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_uint32_euint32",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_uint32_euint32",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rem_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rem_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rem_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "resEbool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resEuint128",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resEuint16",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resEuint256",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resEuint32",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resEuint64",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "resEuint8", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sub_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub_uint32_euint32",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_uint32_euint32",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "add_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_uint32_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_uint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_uint32_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_uint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "div_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "div_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "div_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_uint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_uint32_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_uint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ge_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ge_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ge_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ge_uint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ge_uint32_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ge_uint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gt_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gt_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gt_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gt_uint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gt_uint32_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gt_uint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "le_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "le_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "le_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "le_uint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "le_uint32_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "le_uint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lt_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lt_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lt_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lt_uint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lt_uint32_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lt_uint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "max_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "max_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "max_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "max_uint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "max_uint32_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "max_uint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "min_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "min_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "min_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "min_uint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "min_uint32_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "min_uint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mul_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mul_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mul_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mul_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mul_uint32_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mul_uint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_uint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_uint32_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_uint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_uint32_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_uint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rem_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rem_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rem_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resEbool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resEuint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resEuint16", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resEuint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resEuint32", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resEuint64", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resEuint8", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sub_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sub_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sub_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sub_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sub_uint32_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sub_uint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_uint32_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_uint64_euint64",
    data: BytesLike
  ): Result;
}

export namespace DebugVerifyEvent {
  export type InputTuple = [
    inputHandle: BytesLike,
    inputProof: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    inputHandle: string,
    inputProof: string,
    result: string
  ];
  export interface OutputObject {
    inputHandle: string;
    inputProof: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHEVMTestSuite6 extends BaseContract {
  connect(runner?: ContractRunner | null): FHEVMTestSuite6;
  waitForDeployment(): Promise<this>;

  interface: FHEVMTestSuite6Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  add_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  add_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  add_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  add_uint32_euint32: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  add_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_uint32_euint32: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  div_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  div_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  div_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_uint16_euint16: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_uint32_euint32: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ge_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ge_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ge_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ge_uint16_euint16: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ge_uint32_euint32: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ge_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  gt_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  gt_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  gt_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  gt_uint16_euint16: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  gt_uint32_euint32: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  gt_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  le_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  le_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  le_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  le_uint16_euint16: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  le_uint32_euint32: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  le_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  lt_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  lt_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  lt_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  lt_uint16_euint16: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  lt_uint32_euint32: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  lt_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  max_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  max_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  max_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  max_uint16_euint16: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  max_uint32_euint32: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  max_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  min_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  min_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  min_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  min_uint16_euint16: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  min_uint32_euint32: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  min_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  mul_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  mul_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  mul_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  mul_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  mul_uint32_euint32: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  mul_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_uint16_euint16: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_uint32_euint32: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_uint32_euint32: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rem_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rem_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rem_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  resEbool: TypedContractMethod<[], [string], "view">;

  resEuint128: TypedContractMethod<[], [string], "view">;

  resEuint16: TypedContractMethod<[], [string], "view">;

  resEuint256: TypedContractMethod<[], [string], "view">;

  resEuint32: TypedContractMethod<[], [string], "view">;

  resEuint64: TypedContractMethod<[], [string], "view">;

  resEuint8: TypedContractMethod<[], [string], "view">;

  sub_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  sub_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  sub_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  sub_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  sub_uint32_euint32: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  sub_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_uint32_euint32: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "add_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "add_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "add_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "add_uint32_euint32"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "add_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_uint32_euint32"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "div_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "div_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "div_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_uint16_euint16"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_uint32_euint32"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ge_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ge_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ge_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ge_uint16_euint16"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ge_uint32_euint32"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ge_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt_uint16_euint16"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt_uint32_euint32"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "le_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "le_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "le_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "le_uint16_euint16"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "le_uint32_euint32"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "le_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt_uint16_euint16"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt_uint32_euint32"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max_uint16_euint16"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max_uint32_euint32"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "min_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "min_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "min_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "min_uint16_euint16"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "min_uint32_euint32"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "min_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mul_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mul_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mul_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mul_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mul_uint32_euint32"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mul_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_uint16_euint16"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_uint32_euint32"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_uint32_euint32"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rem_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rem_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rem_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resEbool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint128"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint16"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint256"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint32"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint64"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint8"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sub_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub_uint32_euint32"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_uint32_euint32"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DebugVerify"
  ): TypedContractEvent<
    DebugVerifyEvent.InputTuple,
    DebugVerifyEvent.OutputTuple,
    DebugVerifyEvent.OutputObject
  >;

  filters: {
    "DebugVerify(bytes32,bytes,bytes32)": TypedContractEvent<
      DebugVerifyEvent.InputTuple,
      DebugVerifyEvent.OutputTuple,
      DebugVerifyEvent.OutputObject
    >;
    DebugVerify: TypedContractEvent<
      DebugVerifyEvent.InputTuple,
      DebugVerifyEvent.OutputTuple,
      DebugVerifyEvent.OutputObject
    >;
  };
}
