/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable2StepUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable2StepUpgradeable__factory>;
    getContractFactory(
      name: "OwnableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnableUpgradeable__factory>;
    getContractFactory(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Initializable__factory>;
    getContractFactory(
      name: "UUPSUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UUPSUpgradeable__factory>;
    getContractFactory(
      name: "ContextUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ContextUpgradeable__factory>;
    getContractFactory(
      name: "PausableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PausableUpgradeable__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Ownable2Step",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable2Step__factory>;
    getContractFactory(
      name: "IERC1822Proxiable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1822Proxiable__factory>;
    getContractFactory(
      name: "IERC1967",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1967__factory>;
    getContractFactory(
      name: "IERC5267",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC5267__factory>;
    getContractFactory(
      name: "IBeacon",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBeacon__factory>;
    getContractFactory(
      name: "ERC1967Utils",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1967Utils__factory>;
    getContractFactory(
      name: "Address",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Address__factory>;
    getContractFactory(
      name: "ECDSA",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ECDSA__factory>;
    getContractFactory(
      name: "Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Errors__factory>;
    getContractFactory(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeCast__factory>;
    getContractFactory(
      name: "Strings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Strings__factory>;
    getContractFactory(
      name: "DecryptionOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DecryptionOracle__factory>;
    getContractFactory(
      name: "ACL",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ACL__factory>;
    getContractFactory(
      name: "ACLEvents",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ACLEvents__factory>;
    getContractFactory(
      name: "FHEEvents",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEEvents__factory>;
    getContractFactory(
      name: "FHEVMExecutor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEVMExecutor__factory>;
    getContractFactory(
      name: "IInputVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IInputVerifier__factory>;
    getContractFactory(
      name: "HCULimit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HCULimit__factory>;
    getContractFactory(
      name: "InputVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InputVerifier__factory>;
    getContractFactory(
      name: "KMSVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KMSVerifier__factory>;
    getContractFactory(
      name: "EIP712UpgradeableCrossChain",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP712UpgradeableCrossChain__factory>;
    getContractFactory(
      name: "EmptyUUPSProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EmptyUUPSProxy__factory>;
    getContractFactory(
      name: "UUPSUpgradeableEmptyProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UUPSUpgradeableEmptyProxy__factory>;
    getContractFactory(
      name: "DecryptionOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DecryptionOracle__factory>;
    getContractFactory(
      name: "ACLUpgradedExample",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ACLUpgradedExample__factory>;
    getContractFactory(
      name: "ACLUpgradedExample2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ACLUpgradedExample2__factory>;
    getContractFactory(
      name: "Counter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Counter__factory>;
    getContractFactory(
      name: "DecryptionOracleUpgradedExample",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DecryptionOracleUpgradedExample__factory>;
    getContractFactory(
      name: "EncryptedERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EncryptedERC20__factory>;
    getContractFactory(
      name: "FHEVMExecutorUpgradedExample",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEVMExecutorUpgradedExample__factory>;
    getContractFactory(
      name: "HCULimitTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HCULimitTest__factory>;
    getContractFactory(
      name: "HCULimitUpgradedExample",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HCULimitUpgradedExample__factory>;
    getContractFactory(
      name: "KMSVerifierUpgradedExample",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KMSVerifierUpgradedExample__factory>;
    getContractFactory(
      name: "MakePubliclyDecryptable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MakePubliclyDecryptable__factory>;
    getContractFactory(
      name: "Rand",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Rand__factory>;
    getContractFactory(
      name: "Reencrypt",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Reencrypt__factory>;
    getContractFactory(
      name: "Regression1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Regression1__factory>;
    getContractFactory(
      name: "SmartAccount",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SmartAccount__factory>;
    getContractFactory(
      name: "TestAsyncDecrypt",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestAsyncDecrypt__factory>;
    getContractFactory(
      name: "TestInput",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestInput__factory>;
    getContractFactory(
      name: "FHEVMManualTestSuite",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEVMManualTestSuite__factory>;
    getContractFactory(
      name: "FHEVMTestSuite1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEVMTestSuite1__factory>;
    getContractFactory(
      name: "FHEVMTestSuite2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEVMTestSuite2__factory>;
    getContractFactory(
      name: "FHEVMTestSuite3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEVMTestSuite3__factory>;
    getContractFactory(
      name: "FHEVMTestSuite4",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEVMTestSuite4__factory>;
    getContractFactory(
      name: "FHEVMTestSuite5",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEVMTestSuite5__factory>;
    getContractFactory(
      name: "FHEVMTestSuite6",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEVMTestSuite6__factory>;
    getContractFactory(
      name: "FHEVMTestSuite7",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEVMTestSuite7__factory>;
    getContractFactory(
      name: "SubContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SubContract__factory>;
    getContractFactory(
      name: "SubContractCreate",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SubContractCreate__factory>;
    getContractFactory(
      name: "SubContractCreateFail",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SubContractCreateFail__factory>;
    getContractFactory(
      name: "TracingSubCalls",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TracingSubCalls__factory>;
    getContractFactory(
      name: "FHE",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHE__factory>;
    getContractFactory(
      name: "IDecryptionOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDecryptionOracle__factory>;
    getContractFactory(
      name: "IKMSVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKMSVerifier__factory>;
    getContractFactory(
      name: "IACL",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IACL__factory>;
    getContractFactory(
      name: "IFHEVMExecutor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFHEVMExecutor__factory>;
    getContractFactory(
      name: "IInputVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IInputVerifier__factory>;
    getContractFactory(
      name: "Impl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Impl__factory>;

    getContractAt(
      name: "Ownable2StepUpgradeable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable2StepUpgradeable>;
    getContractAt(
      name: "OwnableUpgradeable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnableUpgradeable>;
    getContractAt(
      name: "Initializable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Initializable>;
    getContractAt(
      name: "UUPSUpgradeable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.UUPSUpgradeable>;
    getContractAt(
      name: "ContextUpgradeable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ContextUpgradeable>;
    getContractAt(
      name: "PausableUpgradeable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PausableUpgradeable>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Ownable2Step",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable2Step>;
    getContractAt(
      name: "IERC1822Proxiable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1822Proxiable>;
    getContractAt(
      name: "IERC1967",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1967>;
    getContractAt(
      name: "IERC5267",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC5267>;
    getContractAt(
      name: "IBeacon",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBeacon>;
    getContractAt(
      name: "ERC1967Utils",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1967Utils>;
    getContractAt(
      name: "Address",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Address>;
    getContractAt(
      name: "ECDSA",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ECDSA>;
    getContractAt(
      name: "Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Errors>;
    getContractAt(
      name: "SafeCast",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeCast>;
    getContractAt(
      name: "Strings",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Strings>;
    getContractAt(
      name: "DecryptionOracle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DecryptionOracle>;
    getContractAt(
      name: "ACL",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ACL>;
    getContractAt(
      name: "ACLEvents",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ACLEvents>;
    getContractAt(
      name: "FHEEvents",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEEvents>;
    getContractAt(
      name: "FHEVMExecutor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEVMExecutor>;
    getContractAt(
      name: "IInputVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IInputVerifier>;
    getContractAt(
      name: "HCULimit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HCULimit>;
    getContractAt(
      name: "InputVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.InputVerifier>;
    getContractAt(
      name: "KMSVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.KMSVerifier>;
    getContractAt(
      name: "EIP712UpgradeableCrossChain",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EIP712UpgradeableCrossChain>;
    getContractAt(
      name: "EmptyUUPSProxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EmptyUUPSProxy>;
    getContractAt(
      name: "UUPSUpgradeableEmptyProxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.UUPSUpgradeableEmptyProxy>;
    getContractAt(
      name: "DecryptionOracle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DecryptionOracle>;
    getContractAt(
      name: "ACLUpgradedExample",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ACLUpgradedExample>;
    getContractAt(
      name: "ACLUpgradedExample2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ACLUpgradedExample2>;
    getContractAt(
      name: "Counter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Counter>;
    getContractAt(
      name: "DecryptionOracleUpgradedExample",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DecryptionOracleUpgradedExample>;
    getContractAt(
      name: "EncryptedERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EncryptedERC20>;
    getContractAt(
      name: "FHEVMExecutorUpgradedExample",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEVMExecutorUpgradedExample>;
    getContractAt(
      name: "HCULimitTest",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HCULimitTest>;
    getContractAt(
      name: "HCULimitUpgradedExample",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HCULimitUpgradedExample>;
    getContractAt(
      name: "KMSVerifierUpgradedExample",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.KMSVerifierUpgradedExample>;
    getContractAt(
      name: "MakePubliclyDecryptable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MakePubliclyDecryptable>;
    getContractAt(
      name: "Rand",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Rand>;
    getContractAt(
      name: "Reencrypt",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Reencrypt>;
    getContractAt(
      name: "Regression1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Regression1>;
    getContractAt(
      name: "SmartAccount",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SmartAccount>;
    getContractAt(
      name: "TestAsyncDecrypt",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TestAsyncDecrypt>;
    getContractAt(
      name: "TestInput",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TestInput>;
    getContractAt(
      name: "FHEVMManualTestSuite",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEVMManualTestSuite>;
    getContractAt(
      name: "FHEVMTestSuite1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEVMTestSuite1>;
    getContractAt(
      name: "FHEVMTestSuite2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEVMTestSuite2>;
    getContractAt(
      name: "FHEVMTestSuite3",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEVMTestSuite3>;
    getContractAt(
      name: "FHEVMTestSuite4",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEVMTestSuite4>;
    getContractAt(
      name: "FHEVMTestSuite5",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEVMTestSuite5>;
    getContractAt(
      name: "FHEVMTestSuite6",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEVMTestSuite6>;
    getContractAt(
      name: "FHEVMTestSuite7",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEVMTestSuite7>;
    getContractAt(
      name: "SubContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SubContract>;
    getContractAt(
      name: "SubContractCreate",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SubContractCreate>;
    getContractAt(
      name: "SubContractCreateFail",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SubContractCreateFail>;
    getContractAt(
      name: "TracingSubCalls",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TracingSubCalls>;
    getContractAt(
      name: "FHE",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHE>;
    getContractAt(
      name: "IDecryptionOracle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDecryptionOracle>;
    getContractAt(
      name: "IKMSVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IKMSVerifier>;
    getContractAt(
      name: "IACL",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IACL>;
    getContractAt(
      name: "IFHEVMExecutor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFHEVMExecutor>;
    getContractAt(
      name: "IInputVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IInputVerifier>;
    getContractAt(
      name: "Impl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Impl>;

    deployContract(
      name: "Ownable2StepUpgradeable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable2StepUpgradeable>;
    deployContract(
      name: "OwnableUpgradeable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OwnableUpgradeable>;
    deployContract(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Initializable>;
    deployContract(
      name: "UUPSUpgradeable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UUPSUpgradeable>;
    deployContract(
      name: "ContextUpgradeable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ContextUpgradeable>;
    deployContract(
      name: "PausableUpgradeable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PausableUpgradeable>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "Ownable2Step",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable2Step>;
    deployContract(
      name: "IERC1822Proxiable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1822Proxiable>;
    deployContract(
      name: "IERC1967",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1967>;
    deployContract(
      name: "IERC5267",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC5267>;
    deployContract(
      name: "IBeacon",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBeacon>;
    deployContract(
      name: "ERC1967Utils",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1967Utils>;
    deployContract(
      name: "Address",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Address>;
    deployContract(
      name: "ECDSA",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ECDSA>;
    deployContract(
      name: "Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Errors>;
    deployContract(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "Strings",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "DecryptionOracle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DecryptionOracle>;
    deployContract(
      name: "ACL",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ACL>;
    deployContract(
      name: "ACLEvents",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ACLEvents>;
    deployContract(
      name: "FHEEvents",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEEvents>;
    deployContract(
      name: "FHEVMExecutor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMExecutor>;
    deployContract(
      name: "IInputVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInputVerifier>;
    deployContract(
      name: "HCULimit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HCULimit>;
    deployContract(
      name: "InputVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InputVerifier>;
    deployContract(
      name: "KMSVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.KMSVerifier>;
    deployContract(
      name: "EIP712UpgradeableCrossChain",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EIP712UpgradeableCrossChain>;
    deployContract(
      name: "EmptyUUPSProxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EmptyUUPSProxy>;
    deployContract(
      name: "UUPSUpgradeableEmptyProxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UUPSUpgradeableEmptyProxy>;
    deployContract(
      name: "DecryptionOracle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DecryptionOracle>;
    deployContract(
      name: "ACLUpgradedExample",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ACLUpgradedExample>;
    deployContract(
      name: "ACLUpgradedExample2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ACLUpgradedExample2>;
    deployContract(
      name: "Counter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Counter>;
    deployContract(
      name: "DecryptionOracleUpgradedExample",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DecryptionOracleUpgradedExample>;
    deployContract(
      name: "EncryptedERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EncryptedERC20>;
    deployContract(
      name: "FHEVMExecutorUpgradedExample",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMExecutorUpgradedExample>;
    deployContract(
      name: "HCULimitTest",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HCULimitTest>;
    deployContract(
      name: "HCULimitUpgradedExample",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HCULimitUpgradedExample>;
    deployContract(
      name: "KMSVerifierUpgradedExample",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.KMSVerifierUpgradedExample>;
    deployContract(
      name: "MakePubliclyDecryptable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MakePubliclyDecryptable>;
    deployContract(
      name: "Rand",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Rand>;
    deployContract(
      name: "Reencrypt",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Reencrypt>;
    deployContract(
      name: "Regression1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Regression1>;
    deployContract(
      name: "SmartAccount",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartAccount>;
    deployContract(
      name: "TestAsyncDecrypt",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestAsyncDecrypt>;
    deployContract(
      name: "TestInput",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestInput>;
    deployContract(
      name: "FHEVMManualTestSuite",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMManualTestSuite>;
    deployContract(
      name: "FHEVMTestSuite1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMTestSuite1>;
    deployContract(
      name: "FHEVMTestSuite2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMTestSuite2>;
    deployContract(
      name: "FHEVMTestSuite3",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMTestSuite3>;
    deployContract(
      name: "FHEVMTestSuite4",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMTestSuite4>;
    deployContract(
      name: "FHEVMTestSuite5",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMTestSuite5>;
    deployContract(
      name: "FHEVMTestSuite6",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMTestSuite6>;
    deployContract(
      name: "FHEVMTestSuite7",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMTestSuite7>;
    deployContract(
      name: "SubContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SubContract>;
    deployContract(
      name: "SubContractCreate",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SubContractCreate>;
    deployContract(
      name: "SubContractCreateFail",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SubContractCreateFail>;
    deployContract(
      name: "TracingSubCalls",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TracingSubCalls>;
    deployContract(
      name: "FHE",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHE>;
    deployContract(
      name: "IDecryptionOracle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDecryptionOracle>;
    deployContract(
      name: "IKMSVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IKMSVerifier>;
    deployContract(
      name: "IACL",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IACL>;
    deployContract(
      name: "IFHEVMExecutor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFHEVMExecutor>;
    deployContract(
      name: "IInputVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInputVerifier>;
    deployContract(
      name: "Impl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Impl>;

    deployContract(
      name: "Ownable2StepUpgradeable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable2StepUpgradeable>;
    deployContract(
      name: "OwnableUpgradeable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OwnableUpgradeable>;
    deployContract(
      name: "Initializable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Initializable>;
    deployContract(
      name: "UUPSUpgradeable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UUPSUpgradeable>;
    deployContract(
      name: "ContextUpgradeable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ContextUpgradeable>;
    deployContract(
      name: "PausableUpgradeable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PausableUpgradeable>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "Ownable2Step",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable2Step>;
    deployContract(
      name: "IERC1822Proxiable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1822Proxiable>;
    deployContract(
      name: "IERC1967",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1967>;
    deployContract(
      name: "IERC5267",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC5267>;
    deployContract(
      name: "IBeacon",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBeacon>;
    deployContract(
      name: "ERC1967Utils",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1967Utils>;
    deployContract(
      name: "Address",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Address>;
    deployContract(
      name: "ECDSA",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ECDSA>;
    deployContract(
      name: "Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Errors>;
    deployContract(
      name: "SafeCast",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "Strings",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "DecryptionOracle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DecryptionOracle>;
    deployContract(
      name: "ACL",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ACL>;
    deployContract(
      name: "ACLEvents",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ACLEvents>;
    deployContract(
      name: "FHEEvents",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEEvents>;
    deployContract(
      name: "FHEVMExecutor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMExecutor>;
    deployContract(
      name: "IInputVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInputVerifier>;
    deployContract(
      name: "HCULimit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HCULimit>;
    deployContract(
      name: "InputVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InputVerifier>;
    deployContract(
      name: "KMSVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.KMSVerifier>;
    deployContract(
      name: "EIP712UpgradeableCrossChain",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EIP712UpgradeableCrossChain>;
    deployContract(
      name: "EmptyUUPSProxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EmptyUUPSProxy>;
    deployContract(
      name: "UUPSUpgradeableEmptyProxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UUPSUpgradeableEmptyProxy>;
    deployContract(
      name: "DecryptionOracle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DecryptionOracle>;
    deployContract(
      name: "ACLUpgradedExample",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ACLUpgradedExample>;
    deployContract(
      name: "ACLUpgradedExample2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ACLUpgradedExample2>;
    deployContract(
      name: "Counter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Counter>;
    deployContract(
      name: "DecryptionOracleUpgradedExample",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DecryptionOracleUpgradedExample>;
    deployContract(
      name: "EncryptedERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EncryptedERC20>;
    deployContract(
      name: "FHEVMExecutorUpgradedExample",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMExecutorUpgradedExample>;
    deployContract(
      name: "HCULimitTest",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HCULimitTest>;
    deployContract(
      name: "HCULimitUpgradedExample",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HCULimitUpgradedExample>;
    deployContract(
      name: "KMSVerifierUpgradedExample",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.KMSVerifierUpgradedExample>;
    deployContract(
      name: "MakePubliclyDecryptable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MakePubliclyDecryptable>;
    deployContract(
      name: "Rand",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Rand>;
    deployContract(
      name: "Reencrypt",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Reencrypt>;
    deployContract(
      name: "Regression1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Regression1>;
    deployContract(
      name: "SmartAccount",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartAccount>;
    deployContract(
      name: "TestAsyncDecrypt",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestAsyncDecrypt>;
    deployContract(
      name: "TestInput",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestInput>;
    deployContract(
      name: "FHEVMManualTestSuite",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMManualTestSuite>;
    deployContract(
      name: "FHEVMTestSuite1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMTestSuite1>;
    deployContract(
      name: "FHEVMTestSuite2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMTestSuite2>;
    deployContract(
      name: "FHEVMTestSuite3",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMTestSuite3>;
    deployContract(
      name: "FHEVMTestSuite4",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMTestSuite4>;
    deployContract(
      name: "FHEVMTestSuite5",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMTestSuite5>;
    deployContract(
      name: "FHEVMTestSuite6",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMTestSuite6>;
    deployContract(
      name: "FHEVMTestSuite7",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVMTestSuite7>;
    deployContract(
      name: "SubContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SubContract>;
    deployContract(
      name: "SubContractCreate",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SubContractCreate>;
    deployContract(
      name: "SubContractCreateFail",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SubContractCreateFail>;
    deployContract(
      name: "TracingSubCalls",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TracingSubCalls>;
    deployContract(
      name: "FHE",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHE>;
    deployContract(
      name: "IDecryptionOracle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDecryptionOracle>;
    deployContract(
      name: "IKMSVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IKMSVerifier>;
    deployContract(
      name: "IACL",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IACL>;
    deployContract(
      name: "IFHEVMExecutor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFHEVMExecutor>;
    deployContract(
      name: "IInputVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInputVerifier>;
    deployContract(
      name: "Impl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Impl>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
