/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../common";

export interface ACLEventsInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "Allowed"
      | "AllowedForDecryption"
      | "NewDelegation"
      | "RevokedDelegation"
      | "UpdatePauser"
  ): EventFragment;
}

export namespace AllowedEvent {
  export type InputTuple = [
    caller: AddressLike,
    account: AddressLike,
    handle: BytesLike
  ];
  export type OutputTuple = [caller: string, account: string, handle: string];
  export interface OutputObject {
    caller: string;
    account: string;
    handle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AllowedForDecryptionEvent {
  export type InputTuple = [caller: AddressLike, handlesList: BytesLike[]];
  export type OutputTuple = [caller: string, handlesList: string[]];
  export interface OutputObject {
    caller: string;
    handlesList: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewDelegationEvent {
  export type InputTuple = [
    caller: AddressLike,
    delegatee: AddressLike,
    contractAddresses: AddressLike[]
  ];
  export type OutputTuple = [
    caller: string,
    delegatee: string,
    contractAddresses: string[]
  ];
  export interface OutputObject {
    caller: string;
    delegatee: string;
    contractAddresses: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevokedDelegationEvent {
  export type InputTuple = [
    caller: AddressLike,
    delegatee: AddressLike,
    contractAddresses: AddressLike[]
  ];
  export type OutputTuple = [
    caller: string,
    delegatee: string,
    contractAddresses: string[]
  ];
  export interface OutputObject {
    caller: string;
    delegatee: string;
    contractAddresses: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatePauserEvent {
  export type InputTuple = [newPauser: AddressLike];
  export type OutputTuple = [newPauser: string];
  export interface OutputObject {
    newPauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ACLEvents extends BaseContract {
  connect(runner?: ContractRunner | null): ACLEvents;
  waitForDeployment(): Promise<this>;

  interface: ACLEventsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "Allowed"
  ): TypedContractEvent<
    AllowedEvent.InputTuple,
    AllowedEvent.OutputTuple,
    AllowedEvent.OutputObject
  >;
  getEvent(
    key: "AllowedForDecryption"
  ): TypedContractEvent<
    AllowedForDecryptionEvent.InputTuple,
    AllowedForDecryptionEvent.OutputTuple,
    AllowedForDecryptionEvent.OutputObject
  >;
  getEvent(
    key: "NewDelegation"
  ): TypedContractEvent<
    NewDelegationEvent.InputTuple,
    NewDelegationEvent.OutputTuple,
    NewDelegationEvent.OutputObject
  >;
  getEvent(
    key: "RevokedDelegation"
  ): TypedContractEvent<
    RevokedDelegationEvent.InputTuple,
    RevokedDelegationEvent.OutputTuple,
    RevokedDelegationEvent.OutputObject
  >;
  getEvent(
    key: "UpdatePauser"
  ): TypedContractEvent<
    UpdatePauserEvent.InputTuple,
    UpdatePauserEvent.OutputTuple,
    UpdatePauserEvent.OutputObject
  >;

  filters: {
    "Allowed(address,address,bytes32)": TypedContractEvent<
      AllowedEvent.InputTuple,
      AllowedEvent.OutputTuple,
      AllowedEvent.OutputObject
    >;
    Allowed: TypedContractEvent<
      AllowedEvent.InputTuple,
      AllowedEvent.OutputTuple,
      AllowedEvent.OutputObject
    >;

    "AllowedForDecryption(address,bytes32[])": TypedContractEvent<
      AllowedForDecryptionEvent.InputTuple,
      AllowedForDecryptionEvent.OutputTuple,
      AllowedForDecryptionEvent.OutputObject
    >;
    AllowedForDecryption: TypedContractEvent<
      AllowedForDecryptionEvent.InputTuple,
      AllowedForDecryptionEvent.OutputTuple,
      AllowedForDecryptionEvent.OutputObject
    >;

    "NewDelegation(address,address,address[])": TypedContractEvent<
      NewDelegationEvent.InputTuple,
      NewDelegationEvent.OutputTuple,
      NewDelegationEvent.OutputObject
    >;
    NewDelegation: TypedContractEvent<
      NewDelegationEvent.InputTuple,
      NewDelegationEvent.OutputTuple,
      NewDelegationEvent.OutputObject
    >;

    "RevokedDelegation(address,address,address[])": TypedContractEvent<
      RevokedDelegationEvent.InputTuple,
      RevokedDelegationEvent.OutputTuple,
      RevokedDelegationEvent.OutputObject
    >;
    RevokedDelegation: TypedContractEvent<
      RevokedDelegationEvent.InputTuple,
      RevokedDelegationEvent.OutputTuple,
      RevokedDelegationEvent.OutputObject
    >;

    "UpdatePauser(address)": TypedContractEvent<
      UpdatePauserEvent.InputTuple,
      UpdatePauserEvent.OutputTuple,
      UpdatePauserEvent.OutputObject
    >;
    UpdatePauser: TypedContractEvent<
      UpdatePauserEvent.InputTuple,
      UpdatePauserEvent.OutputTuple,
      UpdatePauserEvent.OutputObject
    >;
  };
}
