/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FHEVMTestSuite7Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "and_euint256_uint256"
      | "and_uint256_euint256"
      | "eq_euint256_uint256"
      | "eq_uint128_euint128"
      | "eq_uint256_euint256"
      | "ge_euint128_uint128"
      | "ge_uint128_euint128"
      | "gt_euint128_uint128"
      | "gt_uint128_euint128"
      | "le_euint128_uint128"
      | "le_uint128_euint128"
      | "lt_euint128_uint128"
      | "lt_uint128_euint128"
      | "max_euint128_uint128"
      | "max_uint128_euint128"
      | "min_euint128_uint128"
      | "min_uint128_euint128"
      | "ne_euint128_uint128"
      | "ne_euint256_uint256"
      | "ne_uint128_euint128"
      | "ne_uint256_euint256"
      | "neg_euint128"
      | "neg_euint16"
      | "neg_euint256"
      | "neg_euint32"
      | "neg_euint64"
      | "neg_euint8"
      | "not_euint128"
      | "not_euint16"
      | "not_euint256"
      | "not_euint32"
      | "not_euint64"
      | "not_euint8"
      | "or_euint256_uint256"
      | "or_uint256_euint256"
      | "resEbool"
      | "resEuint128"
      | "resEuint16"
      | "resEuint256"
      | "resEuint32"
      | "resEuint64"
      | "resEuint8"
      | "rotl_euint128_euint8"
      | "rotl_euint128_uint8"
      | "rotl_euint16_euint8"
      | "rotl_euint16_uint8"
      | "rotl_euint256_euint8"
      | "rotl_euint256_uint8"
      | "rotl_euint32_euint8"
      | "rotl_euint32_uint8"
      | "rotl_euint64_euint8"
      | "rotl_euint64_uint8"
      | "rotl_euint8_euint8"
      | "rotl_euint8_uint8"
      | "rotr_euint128_euint8"
      | "rotr_euint128_uint8"
      | "rotr_euint16_euint8"
      | "rotr_euint16_uint8"
      | "rotr_euint256_euint8"
      | "rotr_euint256_uint8"
      | "rotr_euint32_euint8"
      | "rotr_euint32_uint8"
      | "rotr_euint64_euint8"
      | "rotr_euint64_uint8"
      | "rotr_euint8_euint8"
      | "rotr_euint8_uint8"
      | "shl_euint128_euint8"
      | "shl_euint128_uint8"
      | "shl_euint16_euint8"
      | "shl_euint16_uint8"
      | "shl_euint256_euint8"
      | "shl_euint256_uint8"
      | "shl_euint32_euint8"
      | "shl_euint32_uint8"
      | "shl_euint64_euint8"
      | "shl_euint64_uint8"
      | "shl_euint8_euint8"
      | "shl_euint8_uint8"
      | "shr_euint128_euint8"
      | "shr_euint128_uint8"
      | "shr_euint16_euint8"
      | "shr_euint16_uint8"
      | "shr_euint256_euint8"
      | "shr_euint256_uint8"
      | "shr_euint32_euint8"
      | "shr_euint32_uint8"
      | "shr_euint64_euint8"
      | "shr_euint64_uint8"
      | "shr_euint8_euint8"
      | "shr_euint8_uint8"
      | "xor_euint256_uint256"
      | "xor_uint256_euint256"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DebugVerify"): EventFragment;

  encodeFunctionData(
    functionFragment: "and_euint256_uint256",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_uint256_euint256",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint256_uint256",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_uint256_euint256",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ge_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ge_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "min_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "min_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint256_uint256",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_uint256_euint256",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "neg_euint128",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "neg_euint16",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "neg_euint256",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "neg_euint32",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "neg_euint64",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "neg_euint8",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "not_euint128",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "not_euint16",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "not_euint256",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "not_euint32",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "not_euint64",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "not_euint8",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint256_uint256",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_uint256_euint256",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "resEbool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resEuint128",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resEuint16",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resEuint256",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resEuint32",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resEuint64",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "resEuint8", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rotl_euint128_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotl_euint128_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotl_euint16_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotl_euint16_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotl_euint256_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotl_euint256_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotl_euint32_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotl_euint32_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotl_euint64_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotl_euint64_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotl_euint8_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotl_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotr_euint128_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotr_euint128_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotr_euint16_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotr_euint16_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotr_euint256_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotr_euint256_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotr_euint32_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotr_euint32_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotr_euint64_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotr_euint64_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotr_euint8_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotr_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl_euint128_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl_euint128_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl_euint16_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl_euint16_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl_euint256_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl_euint256_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl_euint32_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl_euint32_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl_euint64_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl_euint64_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl_euint8_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shr_euint128_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shr_euint128_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shr_euint16_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shr_euint16_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shr_euint256_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shr_euint256_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shr_euint32_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shr_euint32_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shr_euint64_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shr_euint64_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shr_euint8_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shr_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint256_uint256",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_uint256_euint256",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "and_euint256_uint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_uint256_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint256_uint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_uint256_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ge_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ge_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gt_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gt_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "le_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "le_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lt_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lt_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "max_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "max_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "min_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "min_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint256_uint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_uint256_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "neg_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "neg_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "neg_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "neg_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "neg_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "neg_euint8", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "not_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "not_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "not_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "not_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "not_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "not_euint8", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "or_euint256_uint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_uint256_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resEbool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resEuint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resEuint16", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resEuint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resEuint32", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resEuint64", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resEuint8", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rotl_euint128_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotl_euint128_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotl_euint16_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotl_euint16_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotl_euint256_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotl_euint256_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotl_euint32_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotl_euint32_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotl_euint64_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotl_euint64_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotl_euint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotl_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotr_euint128_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotr_euint128_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotr_euint16_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotr_euint16_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotr_euint256_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotr_euint256_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotr_euint32_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotr_euint32_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotr_euint64_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotr_euint64_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotr_euint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotr_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shl_euint128_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shl_euint128_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shl_euint16_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shl_euint16_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shl_euint256_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shl_euint256_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shl_euint32_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shl_euint32_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shl_euint64_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shl_euint64_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shl_euint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shl_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shr_euint128_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shr_euint128_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shr_euint16_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shr_euint16_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shr_euint256_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shr_euint256_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shr_euint32_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shr_euint32_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shr_euint64_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shr_euint64_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shr_euint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shr_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint256_uint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_uint256_euint256",
    data: BytesLike
  ): Result;
}

export namespace DebugVerifyEvent {
  export type InputTuple = [
    inputHandle: BytesLike,
    inputProof: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    inputHandle: string,
    inputProof: string,
    result: string
  ];
  export interface OutputObject {
    inputHandle: string;
    inputProof: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHEVMTestSuite7 extends BaseContract {
  connect(runner?: ContractRunner | null): FHEVMTestSuite7;
  waitForDeployment(): Promise<this>;

  interface: FHEVMTestSuite7Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  and_euint256_uint256: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_uint256_euint256: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint256_uint256: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_uint256_euint256: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ge_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ge_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  gt_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  gt_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  le_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  le_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  lt_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  lt_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  max_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  max_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  min_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  min_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint256_uint256: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_uint256_euint256: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  neg_euint128: TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  neg_euint16: TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  neg_euint256: TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  neg_euint32: TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  neg_euint64: TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  neg_euint8: TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  not_euint128: TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  not_euint16: TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  not_euint256: TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  not_euint32: TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  not_euint64: TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  not_euint8: TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint256_uint256: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_uint256_euint256: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  resEbool: TypedContractMethod<[], [string], "view">;

  resEuint128: TypedContractMethod<[], [string], "view">;

  resEuint16: TypedContractMethod<[], [string], "view">;

  resEuint256: TypedContractMethod<[], [string], "view">;

  resEuint32: TypedContractMethod<[], [string], "view">;

  resEuint64: TypedContractMethod<[], [string], "view">;

  resEuint8: TypedContractMethod<[], [string], "view">;

  rotl_euint128_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotl_euint128_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotl_euint16_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotl_euint16_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotl_euint256_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotl_euint256_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotl_euint32_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotl_euint32_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotl_euint64_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotl_euint64_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotl_euint8_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotl_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotr_euint128_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotr_euint128_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotr_euint16_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotr_euint16_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotr_euint256_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotr_euint256_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotr_euint32_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotr_euint32_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotr_euint64_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotr_euint64_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotr_euint8_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotr_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shl_euint128_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shl_euint128_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shl_euint16_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shl_euint16_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shl_euint256_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shl_euint256_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shl_euint32_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shl_euint32_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shl_euint64_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shl_euint64_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shl_euint8_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shl_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shr_euint128_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shr_euint128_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shr_euint16_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shr_euint16_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shr_euint256_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shr_euint256_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shr_euint32_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shr_euint32_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shr_euint64_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shr_euint64_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shr_euint8_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shr_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint256_uint256: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_uint256_euint256: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "and_euint256_uint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_uint256_euint256"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint256_uint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_uint256_euint256"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ge_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ge_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "le_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "le_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "min_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "min_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint256_uint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_uint256_euint256"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "neg_euint128"
  ): TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "neg_euint16"
  ): TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "neg_euint256"
  ): TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "neg_euint32"
  ): TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "neg_euint64"
  ): TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "neg_euint8"
  ): TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "not_euint128"
  ): TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "not_euint16"
  ): TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "not_euint256"
  ): TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "not_euint32"
  ): TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "not_euint64"
  ): TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "not_euint8"
  ): TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint256_uint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_uint256_euint256"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resEbool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint128"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint16"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint256"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint32"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint64"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint8"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rotl_euint128_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotl_euint128_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotl_euint16_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotl_euint16_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotl_euint256_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotl_euint256_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotl_euint32_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotl_euint32_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotl_euint64_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotl_euint64_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotl_euint8_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotl_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotr_euint128_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotr_euint128_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotr_euint16_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotr_euint16_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotr_euint256_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotr_euint256_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotr_euint32_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotr_euint32_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotr_euint64_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotr_euint64_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotr_euint8_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotr_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl_euint128_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl_euint128_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl_euint16_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl_euint16_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl_euint256_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl_euint256_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl_euint32_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl_euint32_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl_euint64_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl_euint64_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl_euint8_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shr_euint128_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shr_euint128_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shr_euint16_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shr_euint16_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shr_euint256_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shr_euint256_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shr_euint32_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shr_euint32_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shr_euint64_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shr_euint64_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shr_euint8_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shr_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint256_uint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_uint256_euint256"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DebugVerify"
  ): TypedContractEvent<
    DebugVerifyEvent.InputTuple,
    DebugVerifyEvent.OutputTuple,
    DebugVerifyEvent.OutputObject
  >;

  filters: {
    "DebugVerify(bytes32,bytes,bytes32)": TypedContractEvent<
      DebugVerifyEvent.InputTuple,
      DebugVerifyEvent.OutputTuple,
      DebugVerifyEvent.OutputObject
    >;
    DebugVerify: TypedContractEvent<
      DebugVerifyEvent.InputTuple,
      DebugVerifyEvent.OutputTuple,
      DebugVerifyEvent.OutputObject
    >;
  };
}
