/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  SubContractCreate,
  SubContractCreateInterface,
} from "../../../examples/TracingSubCalls.sol/SubContractCreate";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint64",
        name: "input",
        type: "uint64",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b506040516101ab3803806101ab83398101604081905261002e91610116565b6100378161003e565b505061018a565b5f6100536001600160401b0383166005610059565b92915050565b7fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea60154604051639cd07acb60e01b81525f917fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea600916001600160a01b0390911690639cd07acb906100ce9087908790600401610143565b6020604051808303815f875af11580156100ea573d5f803e3d5ffd5b505050506040513d601f19601f8201168201806040525081019061010e9190610173565b949350505050565b5f60208284031215610126575f80fd5b81516001600160401b038116811461013c575f80fd5b9392505050565b828152604081016054831061016657634e487b7160e01b5f52602160045260245ffd5b8260208301529392505050565b5f60208284031215610183575f80fd5b5051919050565b6015806101965f395ff3fe60806040525f80fdfea164736f6c6343000818000a";

type SubContractCreateConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SubContractCreateConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SubContractCreate__factory extends ContractFactory {
  constructor(...args: SubContractCreateConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    input: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(input, overrides || {});
  }
  override deploy(
    input: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(input, overrides || {}) as Promise<
      SubContractCreate & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SubContractCreate__factory {
    return super.connect(runner) as SubContractCreate__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SubContractCreateInterface {
    return new Interface(_abi) as SubContractCreateInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SubContractCreate {
    return new Contract(address, _abi, runner) as unknown as SubContractCreate;
  }
}
